/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2023-06-19 01:45:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <style>\r\n");
      out.write("    body {\r\n");
      out.write("      background-color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-container {\r\n");
      out.write("      margin-top: 100px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("     .custom-btn {\r\n");
      out.write("    background-color: #ffffff;\r\n");
      out.write("    border-color: #000000;\r\n");
      out.write("  color: #000000;\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    .login-form {\r\n");
      out.write("      background-color: #ffffff;\r\n");
      out.write("      padding: 40px;\r\n");
      out.write("      border-radius: 12px;\r\n");
      out.write("      box-shadow: 0px 0px 20px 0px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-form h2 {\r\n");
      out.write("      margin-bottom: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-form .form-control {\r\n");
      out.write("      border-radius: 2px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-form .btn {\r\n");
      out.write("      border-radius: 20px;\r\n");
      out.write("      transition: all 0.5s;\r\n");
      out.write("      \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-form .btn:hover {\r\n");
      out.write("      transform: scale(1.05);\r\n");
      out.write("      background-color:black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-form .btn-block {\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-form .remember-checkbox {\r\n");
      out.write("      margin-top: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-form .forgot-password {\r\n");
      out.write("      text-align: right;\r\n");
      out.write("      margin-top: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-form .forgot-password a {\r\n");
      out.write("      color: #777777;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-form .image-container {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      margin-bottom: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-form .image-container img {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-form .input-group-prepend .input-group-text {\r\n");
      out.write("      border-radius: 2px 0 0 2px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-form .button-container {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-form .button-container .btn {\r\n");
      out.write("      flex: 1;\r\n");
      out.write("      margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("  <script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("      $(\".login-form\").hide().fadeIn(2000);\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row justify-content-center\">\r\n");
      out.write("      <div class=\"col-md-10 login-container\">\r\n");
      out.write("        <form class=\"login-form\">\r\n");
      out.write("          <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("              <div class=\"image-container\">\r\n");
      out.write("                <img src=\"https://img.freepik.com/vetores-premium/cafe-desenhado-a-mao-com-biscoito_6011-201.jpg\" style=\"height:60%; width:60%;\" alt=\"Café\">\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("              <h2>Login</h2>\r\n");
      out.write("              <div class=\"input-group mb-3\">\r\n");
      out.write("                <div class=\"input-group-prepend\">\r\n");
      out.write("                  <span class=\"input-group-text\"><i class=\"fas fa-user\"></i></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" placeholder=\"Email\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"input-group mb-3\">\r\n");
      out.write("                <div class=\"input-group-prepend\">\r\n");
      out.write("                  <span class=\"input-group-text\"><i class=\"fas fa-lock\"></i></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"password\" class=\"form-control\" placeholder=\"Senha\" required>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"button-container\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary custom-btn\">Entrar</button>\r\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary custom-btn\">Cadastrar</button>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"remember-checkbox\">\r\n");
      out.write("                <label>\r\n");
      out.write("                  <input type=\"checkbox\"> Lembre-me\r\n");
      out.write("                </label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"forgot-password\">\r\n");
      out.write("                <a href=\"#\">Esqueceu a Senha?</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
