/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2023-07-02 17:45:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.View;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Assests.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("\r\n");
      out.write("  <article>\r\n");
      out.write("    <div id=\"demo\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("      <ol class=\"carousel-indicators\">\r\n");
      out.write("        <li data-bs-target=\"#demo\" data-bs-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("        <li data-bs-target=\"#demo\" data-bs-slide-to=\"1\"></li>\r\n");
      out.write("        <li data-bs-target=\"#demo\" data-bs-slide-to=\"2\"></li>\r\n");
      out.write("      </ol>\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("      <div class=\"carousel-inner\">\r\n");
      out.write(" \t\t <div class=\"carousel-item active\">\r\n");
      out.write("    \t\t<img src=\"https://stories.starbucks.com/uploads/sites/25/2021/12/image-1.png\" alt=\"Los Angeles\"\r\n");
      out.write("     \t\t\t class=\"d-block\" style=\"width:100%; height:80vh;\">\r\n");
      out.write(" \t\t </div>\r\n");
      out.write("          <div class=\"carousel-item\">\r\n");
      out.write("          <img src=\"https://stories.starbucks.com/uploads/2022/08/MicrosoftTeams-image-7.jpg\" alt=\"Chicago\" class=\"d-block\"\r\n");
      out.write("           style=\"width:100%; height:80vh;\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\">\r\n");
      out.write("          <img src=\"https://www.cozinhecomomestre.com.br/wp-content/uploads/2022/08/bolo-red-velvet-800x445.jpg\" \r\n");
      out.write("          alt=\"New York\" class=\"d-block\" style=\"width:100%; height:80vh;\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <a class=\"carousel-control-prev\" href=\"#demo\" role=\"button\" data-bs-slide=\"prev\">\r\n");
      out.write("        <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("    \r\n");
      out.write("      </a>\r\n");
      out.write("      <a class=\"carousel-control-next\" href=\"#demo\" role=\"button\" data-bs-slide=\"next\">\r\n");
      out.write("        <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("        \r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"cafe-section\" style=\"margin-top:80px;\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <h2>Bem-vindo Cafeteria Kiki</h2>\r\n");
      out.write("            <p> Em nosso café, você será transportado para cenários deslumbrantes e encontrará os personagens cativantes que conquistaram corações ao redor do mundo. Delicie-se com café e chás especiais preparados com maestria, enquanto desfruta de um ambiente acolhedor e encantador. Deixe-se levar por uma experiência única, onde a fantasia se torna realidade e cada visita é uma jornada memorável. No Café Kiki, a magia está presente em cada detalhe, aguardando ansiosamente por sua visita.</p>\r\n");
      out.write("            <a href=\"#\" class=\"btn btn-primary\">Conheça nossos produtos</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <img src=\"https://1.bp.blogspot.com/-lmWMErJCXbE/UuLBi_iGUKI/AAAAAAAAETQ/rJNxZUwQyCg/s1600/frappuccino.jpg\" alt=\"Cafeteria\" class=\"img-fluid\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"servicos-section\"  style=\"margin-top:80px;\" >\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h2>Nossos Serviços</h2>\r\n");
      out.write("        <div class=\"row\" style=\"margin-top:100px;\">\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"servico-item\">\r\n");
      out.write("              <i class=\"fas fa-coffee\"></i>\r\n");
      out.write("              <h3>Variedade de Cafes</h3>\r\n");
      out.write("              <p>Explore nossa seleção de cafés exclusivos: do clássico Espresso\r\n");
      out.write("               ao suave Cappuccino, do exótico Macchiato ao encorpado Mocha. Delícias para todos os paladares.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"servico-item\">\r\n");
      out.write("              <i class=\"fas fa-mug-hot\"></i>\r\n");
      out.write("              <h3>Ambiente Aconchegante</h3>\r\n");
      out.write("              <p>Acolhedor, charmoso e relaxante. Um refúgio que transborda conforto e encanto.\r\n");
      out.write("               Venha desfrutar do nosso ambiente aconchegante e convidativo.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"servico-item\">\r\n");
      out.write("              <i class=\"fas fa-birthday-cake\"></i>\r\n");
      out.write("              <h3>Cafés Personalizados</h3>\r\n");
      out.write("              <p>Desfrute de cafés personalizados à sua maneira. Escolha entre ingredientes gourmet,\r\n");
      out.write("               diferentes intensidades e opções de adoçantes para criar a sua bebida perfeita.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("  </article>\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
