/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2023-07-05 21:57:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.View;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <style>\r\n");
      out.write("    .pink-text {\r\n");
      out.write("      color: #FFC0CB;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .link {\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("    color:black;\r\n");
      out.write("    }\r\n");
      out.write("    .link:hover{\r\n");
      out.write("    text-decoration:none;\r\n");
      out.write("    transition:color 1s;\r\n");
      out.write("    color:blue;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("     .cafe-name {\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #333;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .cafe-info {\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #666;\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("   .custom-card {\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("   .card-img-top {\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    \r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" style=\"margin-top: 100px;\">\r\n");
      out.write("  <div class=\"row align-items-center\">\r\n");
      out.write("    <div class=\"col-md-6\">\r\n");
      out.write("      <h4 class=\"cafe-name\">Cafeteria Kiki</h4>\r\n");
      out.write("      <p class=\"cafe-info\">Endereço: Rua Guilhermino de Lima - 48</p>\r\n");
      out.write("      <p class=\"cafe-info\">Telefone: (11) 2444-8696</p>   \r\n");
      out.write("      <p class=\"cafe-info\" style=\"color:green;\">Pedido mínimo: R$ 30,00</p>\r\n");
      out.write("      <p id=\"funcionamento\" class=\"cafe-info\">Seg-Sex: 8h-20h / Sáb-Dom: 9h-18h</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-6\">\r\n");
      out.write("      <img src=\"https://graoespecial.com.br/wp-content/uploads/2018/09/foto3.jpg\" alt=\"Imagem da cafeteria\" class=\"img-fluid\" style=\"border-radius: 20px;\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  var divFuncionamento = document.getElementById(\"funcionamento\");\r\n");
      out.write("  var dataHoraAtual = new Date();\r\n");
      out.write("  \r\n");
      out.write("  var diaSemana = dataHoraAtual.getDay(); // 0 (Domingo) a 6 (Sábado)\r\n");
      out.write("  \r\n");
      out.write("  var horarioAbertura;\r\n");
      out.write("  var horarioFechamento;\r\n");
      out.write("  \r\n");
      out.write("  if (diaSemana >= 1 && diaSemana <= 5) {\r\n");
      out.write("    horarioAbertura = new Date(dataHoraAtual.getFullYear(), dataHoraAtual.getMonth(), dataHoraAtual.getDate(), 8, 0, 0); // 8h\r\n");
      out.write("    horarioFechamento = new Date(dataHoraAtual.getFullYear(), dataHoraAtual.getMonth(), dataHoraAtual.getDate(), 20, 0, 0); // 20h\r\n");
      out.write("  } else if (diaSemana === 0 || diaSemana === 6) {\r\n");
      out.write("    horarioAbertura = new Date(dataHoraAtual.getFullYear(), dataHoraAtual.getMonth(), dataHoraAtual.getDate(), 9, 0, 0); // 9h\r\n");
      out.write("    horarioFechamento = new Date(dataHoraAtual.getFullYear(), dataHoraAtual.getMonth(), dataHoraAtual.getDate(), 18, 0, 0); // 18h\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  if (dataHoraAtual >= horarioAbertura && dataHoraAtual <= horarioFechamento) {\r\n");
      out.write("    divFuncionamento.classList.add(\"text-success\");\r\n");
      out.write("  } else {\r\n");
      out.write("    divFuncionamento.classList.add(\"text-danger\");\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container\" style=\"margin-top: 20px;\">\r\n");
      out.write("    <h2>Menu</h2>\r\n");
      out.write(" \r\n");
      out.write("     <i class=\"fas fa-shopping-cart\"></i>\r\n");
      out.write("      <span id=\"cart-count\" class=\"badge\">0</span>\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"container\" style=\"margin-top: 40px;\">\r\n");
      out.write("        <hr style=\"background-color: black;\">\r\n");
      out.write("        <div class=\"row text-center\">\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <h4><a class=\"link\" href=\"#cafes\">Cafés</a></h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <h4><a class=\"link\" href=\"#gelados\">Gelados</a></h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <h4><a class=\"link\" href=\"#cappuccinos\">Cappuccinos</a></h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <h4><a class=\"link\" href=\"#lanches\">Lanches</a></h4>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr style=\"background-color: black;\">\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("           <div style=\"margin-top:20px; margin-bottom:20px;\">\r\n");
      out.write("                <h4><a class=\"link\" href=\"#cafes\">Cafés</a></h4>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://s3-eu-west-1.amazonaws.com/images-ca-1-0-1-eu/tag_photos/original/1736/expresso-pixabay-coffee-3107235_1280.jpg\" alt=\"Café 1\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Café Expresso</h5>\r\n");
      out.write("        <p class=\"card-text\">Café puro, forte e encorpado.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 5,00</p>\r\n");
      out.write("         <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-expresso\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("        <a class=\"btn btn-primary add-btn\" data-index=\"1\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://www.nespresso.com/ncp/res/uploads/recipes/nespresso-recipes-Latte-Macchiato.jpg\" alt=\"Café 2\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Café Latte</h5>\r\n");
      out.write("        <p class=\"card-text\">Café com leite cremoso e suave.</p>\r\n");
      out.write("        \r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 7,50</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-latte\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("         <a class=\"btn btn-primary add-btn\" data-index=\"2\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://images.ctfassets.net/v601h1fyjgba/4mf4LfyiIKLvOw72oPDgD3/cca493e3a33d080f4a7e6eade04af27a/Caf___Mocha.jpg\" alt=\"Café 3\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Café Mocha</h5>\r\n");
      out.write("        <p class=\"card-text\">Café com chocolate e creme de leite.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 6,50</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-cappuccino\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("        <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://lojaschluck.com.br/wp-content/uploads/2020/06/drink-com-licor-de-cafe-cappuccino-schluck.jpg\" alt=\"Café 4\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Café Cappuccino</h5>\r\n");
      out.write("        <p class=\"card-text\">Café com leite vaporizado e espuma de leite.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 8,00</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-latte\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("       <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://www.receiteria.com.br/wp-content/uploads/receitas-de-frappuccino.jpg\" alt=\"Café 5\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Café Frappuccino</h5>\r\n");
      out.write("        <p class=\"card-text\">Café gelado com leite e cobertura de chantilly.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 9,50</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-latte\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("        <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://www.nespresso.com/ncp/res/uploads/recipes/espressomacchiato2BR.jpg\" alt=\"Café 6\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Café Macchiato</h5>\r\n");
      out.write("        <p class=\"card-text\">Café com uma pequena quantidade de leite vaporizado.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 6,00</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-latte\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("         <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t <div style=\"margin-top:20px; margin-bottom:20px;\">\r\n");
      out.write("                <h4><a class=\"link\" href=\"#gelados\">Gelados</a></h4>\r\n");
      out.write("            </div>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://naminhapanela.com/wp-content/uploads/2023/04/Como-fazer-cafe-gelado-735x491.jpg\" alt=\"Café Gelado 1\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Café Gelado Tradicional</h5>\r\n");
      out.write("        <p class=\"card-text\">Café gelado refrescante.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 8,00</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-latte\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("        <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://s2-receitas.glbimg.com/LNG92eVzOcqj_bXb2CL1lzFv-AU=/0x0:200x300/984x0/smart/filters:strip_icc()/s.glbimg.com/po/rc/media/2014/04/22/16_19_45_710_cafe_2.jpg\" alt=\"Café Gelado 2\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Café Gelado com Caramelo</h5>\r\n");
      out.write("        <p class=\"card-text\">Café gelado com calda de caramelo.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 9,50</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-latte\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("       <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://img.cybercook.com.br/receitas/880/cafe-gelado-3.jpeg\" alt=\"Café Gelado 3\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Café Gelado com Chocolate</h5>\r\n");
      out.write("        <p class=\"card-text\">Café gelado com cobertura de chocolate.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 7,50</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-latte\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("        <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  <div style=\"margin-top:20px; margin-bottom:20px;\">\r\n");
      out.write("                <h4><a class=\"link\" href=\"#cappuccinos\">Cappuccinos</a></h4>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://www.tasteofhome.com/wp-content/uploads/2018/01/exps37407_THE1213734_37407_WEB.jpg\" alt=\"Cappuccino 1\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Cappuccino Tradicional</h5>\r\n");
      out.write("        <p class=\"card-text\">Cappuccino clássico com café, leite vaporizado e espuma de leite.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 10,00</p>\r\n");
      out.write("        <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://www.receiteria.com.br/wp-content/uploads/receitas-de-capuccino-cremoso-1.jpg\" alt=\"Cappuccino 2\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Cappuccino de Chocolate</h5>\r\n");
      out.write("        <p class=\"card-text\">Cappuccino com sabor de chocolate e cobertura de chantilly.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 12,50</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-latte\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("        <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://www.cardamomo.news/__export/1634581877970/sites/debate/img/2021/10/18/caramel_macchiato_frappe.jpeg_1753094345.jpeg\" alt=\"Cappuccino 3\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Cappuccino Caramelado</h5>\r\n");
      out.write("        <p class=\"card-text\">Cappuccino com toque de caramelo e chantilly.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 11,00</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-latte\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("       <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div style=\"margin-top:20px; margin-bottom:20px;\">\r\n");
      out.write("                <h4><a class=\"link\" href=\"#lanches\">Lanches</a></h4>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://www.confeiteiradesucesso.com/wp-content/uploads/2019/03/hamburguergourmet-fb.jpg\" alt=\"Lanche 1\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Hambúrguer Clássico</h5>\r\n");
      out.write("        <p class=\"card-text\">Pão, hambúrguer de carne, queijo, alface e tomate.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 15,00</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-latte\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("        <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://boomi.b-cdn.net/wp-content/uploads/2022/06/lanche-ovo-e-abobrinha.jpg\" alt=\"Lanche 2\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Sanduíche Vegetariano</h5>\r\n");
      out.write("        <p class=\"card-text\">Pão integral, alface, tomate, cenoura, queijo e molho especial.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 12,50</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-latte\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("        <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://www.perdigao.com.br/assets/_images/8402c5c5f29ca29d758ca7657d3c4ac29a587edf.webp\" alt=\"Lanche 3\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Wrap de Frango</h5>\r\n");
      out.write("        <p class=\"card-text\">Tortilha de trigo, frango grelhado, alface, tomate e maionese.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 13,00</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-latte\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("        <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://i3.wp.com/whatagirleats.com/wp-content/uploads/2016/04/IMG_4392.jpg\" alt=\"Lanche 4\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Panini Caprese</h5>\r\n");
      out.write("        <p class=\"card-text\">Pão italiano, queijo mozarela, tomate, manjericão e azeite.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 11,50</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-latte\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("         <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <div class=\"card custom-card\" style=\"width: 100%;\">\r\n");
      out.write("      <img class=\"card-img-top\" src=\"https://claudia.abril.com.br/wp-content/uploads/2020/03/club-sandwichcrc3a9dito-ricardo-dc2b4angelo.jpg\" alt=\"Lanche 5\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        <h5 class=\"card-title\">Club Sandwich</h5>\r\n");
      out.write("        <p class=\"card-text\">Pão de forma, frango grelhado, bacon, alface, tomate e maionese.</p>\r\n");
      out.write("        <p class=\"card-text\">Preço: R$ 14,00</p>\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("              <input type=\"number\" id=\"quantity-latte\" class=\"form-control\" value=\"1\">\r\n");
      out.write("            </div>\r\n");
      out.write("        <a class=\"btn btn-primary add-btn\" data-index=\"3\">>Comprar</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"cart\" style=\"margin-top: 20px;\">\r\n");
      out.write("  <h2>Carrinho de Compras</h2>\r\n");
      out.write("  <ul id=\"cart-items\"></ul>\r\n");
      out.write("  <p>Total: R$ <span id=\"cart-total\">0.00</span></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("      var cartItems = [];\r\n");
      out.write("      var cartCount = 0;\r\n");
      out.write("      var itemList = [\r\n");
      out.write("        { name: 'Café Expresso', price: 5.00 },\r\n");
      out.write("        { name: 'Café Latte', price: 7.50 },\r\n");
      out.write("        { name: 'Café Mocha', price: 6.50 },\r\n");
      out.write("        { name: 'Café Cappuccino', price: 8.00 },\r\n");
      out.write("      ];\r\n");
      out.write("\r\n");
      out.write("      function updateCart() {\r\n");
      out.write("        $('#cart-items').empty();\r\n");
      out.write("        var total = 0;\r\n");
      out.write("\r\n");
      out.write("        for (var i = 0; i < cartItems.length; i++) {\r\n");
      out.write("          var item = cartItems[i];\r\n");
      out.write("          var subtotal = item.price * item.quantity;\r\n");
      out.write("          total += subtotal;\r\n");
      out.write("\r\n");
      out.write("          var row = '<tr>';\r\n");
      out.write("          row += '<td>' + item.product + '</td>';\r\n");
      out.write("          row += '<td>R$' + item.price.toFixed(2) + '</td>';\r\n");
      out.write("          row += '<td>' + item.quantity + '</td>';\r\n");
      out.write("          row += '<td><button class=\"btn btn-danger btn-sm remove-btn\" data-index=\"' + i + '\">Remover</button></td>';\r\n");
      out.write("          row += '</tr>';\r\n");
      out.write("\r\n");
      out.write("          $('#cart-items').append(row);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $('#total').text('Total: R$' + total.toFixed(2));\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      function updateCartCount() {\r\n");
      out.write("        $('#cart-count').text(cartCount);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      function addItemToCart(product, price, quantity) {\r\n");
      out.write("        var newItem = {\r\n");
      out.write("          product: product,\r\n");
      out.write("          price: price,\r\n");
      out.write("          quantity: quantity\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        cartItems.push(newItem);\r\n");
      out.write("        cartCount += quantity;\r\n");
      out.write("\r\n");
      out.write("        updateCart();\r\n");
      out.write("        updateCartCount();\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      for (var i = 0; i < itemList.length; i++) {\r\n");
      out.write("        var item = itemList[i];\r\n");
      out.write("\r\n");
      out.write("        var card = '<div class=\"col-md-3\">';\r\n");
      out.write("        card += '<div class=\"card\">';\r\n");
      out.write("        card += '<div class=\"card-body\">';\r\n");
      out.write("        card += '<h5 class=\"card-title\">' + item.name + '</h5>';\r\n");
      out.write("        card += '<p class=\"card-text\">R$' + item.price.toFixed(2) + '</p>';\r\n");
      out.write("        card += '<div class=\"form-group\">';\r\n");
      out.write("        card += '<input type=\"number\" id=\"quantity-' + i + '\" class=\"form-control\" value=\"1\">';\r\n");
      out.write("        card += '</div>';\r\n");
      out.write("        card += '<button class=\"btn btn-primary add-btn\" data-index=\"' + i + '\">Comprar</button>';\r\n");
      out.write("        card += '</div>';\r\n");
      out.write("        card += '</div>';\r\n");
      out.write("        card += '</div>';\r\n");
      out.write("\r\n");
      out.write("        $('#item-list').append(card);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      $(document).on('click', '.add-btn', function() {\r\n");
      out.write("        var index = $(this).data('index');\r\n");
      out.write("        var quantity = parseInt($('#quantity-' + index).val());\r\n");
      out.write("\r\n");
      out.write("        if (quantity && quantity > 0) {\r\n");
      out.write("          var item = itemList[index];\r\n");
      out.write("          addItemToCart(item.name, item.price, quantity);\r\n");
      out.write("          $('#quantity-' + index).val('1');\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      $(document).on('click', '.remove-btn', function() {\r\n");
      out.write("        var index = $(this).data('index');\r\n");
      out.write("        var item = cartItems[index];\r\n");
      out.write("        cartCount -= item.quantity;\r\n");
      out.write("        cartItems.splice(index, 1);\r\n");
      out.write("        updateCart();\r\n");
      out.write("        updateCartCount();\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      $(document).on('click', '#checkout-btn', function() {\r\n");
      out.write("        var total = 0;\r\n");
      out.write("\r\n");
      out.write("        for (var i = 0; i < cartItems.length; i++) {\r\n");
      out.write("          var item = cartItems[i];\r\n");
      out.write("          var subtotal = item.price * item.quantity;\r\n");
      out.write("          total += subtotal;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        var expirationDate = new Date();\r\n");
      out.write("        expirationDate.setFullYear(expirationDate.getFullYear() + 1);\r\n");
      out.write("\r\n");
      out.write("        document.cookie = 'total=' + total.toFixed(2) + '; expires=' + expirationDate.toUTCString() + '; path=/';\r\n");
      out.write("\r\n");
      out.write("        alert('Pedido realizado! Total: R$' + total.toFixed(2));\r\n");
      out.write("      });\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("  <script>\r\n");
      out.write("  // Função para adicionar um item ao carrinho\r\n");
      out.write("  function addToCart(itemIndex) {\r\n");
      out.write("    var item;\r\n");
      out.write("    switch (itemIndex) {\r\n");
      out.write("      case 1:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Expresso',\r\n");
      out.write("          price: 5.00\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 2:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Latte',\r\n");
      out.write("          price: 7.50\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 3:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Mocha',\r\n");
      out.write("          price: 6.50\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 4:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Cappuccino',\r\n");
      out.write("          price: 8.00\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 5:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Frappuccino',\r\n");
      out.write("          price: 9.50\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 6:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Macchiato',\r\n");
      out.write("          price: 6.00\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 7:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Gelado',\r\n");
      out.write("          price: 5.00\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 8:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café com Leite',\r\n");
      out.write("          price: 4.50\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 9:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Descafeinado',\r\n");
      out.write("          price: 5.50\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 10:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Americano',\r\n");
      out.write("          price: 4.00\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Cria um elemento <li> para exibir o item no carrinho\r\n");
      out.write("    var listItem = document.createElement('li');\r\n");
      out.write("    listItem.textContent = item.name + ' - R$ ' + item.price.toFixed(2);\r\n");
      out.write("\r\n");
      out.write("    // Adiciona o item ao carrinho\r\n");
      out.write("    var cartItems = document.getElementById('cart-items');\r\n");
      out.write("    cartItems.appendChild(listItem);\r\n");
      out.write("\r\n");
      out.write("    // Atualiza o total do carrinho\r\n");
      out.write("    var cartTotal = document.getElementById('cart-total');\r\n");
      out.write("    var currentTotal = parseFloat(cartTotal.textContent);\r\n");
      out.write("    var newTotal = currentTotal + item.price;\r\n");
      out.write("    cartTotal.textContent = newTotal.toFixed(2);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  // Adiciona o evento de clique aos botões \"Comprar\"\r\n");
      out.write("  var addButtons = document.getElementsByClassName('add-btn');\r\n");
      out.write("  for (var i = 0; i < addButtons.length; i++) {\r\n");
      out.write("    addButtons[i].addEventListener('Desculpe, mas parece que houve um problema de formatação na resposta anterior. Aqui está o código corrigido para adicionar um carrinho de compras aos itens do menu:\r\n");
      out.write("\r\n");
      out.write("```html\r\n");
      out.write("<script>\r\n");
      out.write("  // Função para adicionar um item ao carrinho\r\n");
      out.write("  function addToCart(itemIndex) {\r\n");
      out.write("    var item;\r\n");
      out.write("    switch (itemIndex) {\r\n");
      out.write("      case 1:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Expresso',\r\n");
      out.write("          price: 5.00\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 2:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Latte',\r\n");
      out.write("          price: 7.50\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 3:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Mocha',\r\n");
      out.write("          price: 6.50\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 4:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Cappuccino',\r\n");
      out.write("          price: 8.00\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 5:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Frappuccino',\r\n");
      out.write("          price: 9.50\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 6:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Macchiato',\r\n");
      out.write("          price: 6.00\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 7:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Gelado',\r\n");
      out.write("          price: 5.00\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 8:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café com Leite',\r\n");
      out.write("          price: 4.50\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 9:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Descafeinado',\r\n");
      out.write("          price: 5.50\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("      case 10:\r\n");
      out.write("        item = {\r\n");
      out.write("          name: 'Café Americano',\r\n");
      out.write("          price: 4.00\r\n");
      out.write("        };\r\n");
      out.write("        break;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Cria um elemento <li> para exibir o item no carrinho\r\n");
      out.write("    var listItem = document.createElement('li');\r\n");
      out.write("    listItem.textContent = item.name + ' - R$ ' + item.price.toFixed(2);\r\n");
      out.write("\r\n");
      out.write("    // Adiciona o item ao carrinho\r\n");
      out.write("    var cartItems = document.getElementById('cart-items');\r\n");
      out.write("    cartItems.appendChild(listItem);\r\n");
      out.write("\r\n");
      out.write("    // Atualiza o total do carrinho\r\n");
      out.write("    var cartTotal = document.getElementById('cart-total');\r\n");
      out.write("    var currentTotal = parseFloat(cartTotal.textContent);\r\n");
      out.write("    var newTotal = currentTotal + item.price;\r\n");
      out.write("    cartTotal.textContent = newTotal.toFixed(2);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  // Adiciona o evento de clique aos botões \"Comprar\"\r\n");
      out.write("  var addButtons = document.getElementsByClassName('add-btn');\r\n");
      out.write("  for (var i = 0; i < addButtons.length; i++) {\r\n");
      out.write("    addButtons[i].addEventListener('click', function(event) {\r\n");
      out.write("      var itemIndex = parseInt(event.target.getAttribute('data-index'));\r\n");
      out.write("      addToCart(itemIndex);\r\n");
      out.write("    });\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
